          <h3>Contact Information</h3>
          <p>
            Questions about the PHP/QAT should be sent to the <a
            href="mailto:php-qa@lists.php.net">PHP/QAT Mailing
            List</a><br />
            Questions regarding this site should be
            sent to the <a href="mailto:zak@nucleus.com">PHP/QAT Site
            Administrator</a><br />
            Bug Reports should be submitted to the official PHP bug list (<a
            href="http://bugs.php.net/">http://bugs.php.net</a>)<br />
            All other questions should be directed to the appropriate PHP <a
            href="http://www.php.net/support.php">mailing list</a>.
          </p>

          <address>
            <?= $CVS_KEYWORDS ?>
          </address>
        </td>
      </tr>
    </table>
  </body>
</html>

