<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <?php include ('../inc/qaweb.css') ?>
    <title>
      <?= $TITLE ?>
    </title>
  </head>
  <body bgcolor="#FFFFFF" marginheight="0" marginwidth="0" background="img/bg_page.gif" text="#000000" link="#0000FF" vlink="#009999">

    <table summary="" cellpadding="0" cellspacing="0" border="0" width="619">
      <tr>
        <td colspan="2" id="titleback"><img src="img/title.gif" alt="PHP/QAT: The PHP Quality Assurance Team" height="41" width="202" border="0" /></td>
      </tr>
      <tr>
        <td align="right" valign="top" colspan="2">
          &gt; &gt; &gt;
          <a href="index.php#news">News</a> |
          <a href="goals.php">Projects and Goals</a> |
          <a href="resources.php">Links &amp; Resources</a> |
          <a href="members.php">Members</a> |
          <a href="howtohelp.php">How to help</a>
          &nbsp;&nbsp;
        </td>
      </tr>
      <tr>
        <td>
          <br />
